<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-6P3KT7T9" failures="1" tests="1" name="testSuite.TestCase01" time="125.746" errors="0" timestamp="2024-09-20T00:20:12 IST" skipped="0">
  <testcase classname="testSuite.TestCase01" name="tc01" time="125.746">
    <failure message="Failed message is displayed!...
	Test is faild due to this,
	Test is faild due to this,
	Element is not visible!...,
	Element is not visible!..." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed message is displayed!...
Test is faild due to this,
Test is faild due to this,
Element is not visible!...,
Element is not visible!...
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at utils.AssertUtils.softAssertAll(AssertUtils.java:20)
at testSuite.TestCase01.tc01(TestCase01.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- tc01 -->
  <system-out/>
</testsuite> <!-- testSuite.TestCase01 -->
